### PR TITLE
feat: skip making exchange rxns reversible

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
1. When making a new ec-model, currently all reversible reactions are made irreversible.
2. The reason for making irreversible is to avoid negative enzyme usage (or in other words: enzyme pseudometabolites being produced instead of consumed).
3. Only reactions that will be extended with enzyme constraints need to be made irreversible, other reactions (e.g. exchange) do not.
4. Making reactions unnecessarily irreversible results in a larger model with numerous loops.

Therefore, the code here only makes reactions reversible if they are associated to a gene.

Note, #193 should be merged to `devel3` first, after which this PR should be based on `devel3`.

**I hereby confirm that I have:**

- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [ ] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Review by johan-gson — COMMENTED** [review]
I wonder if this is really a good idea? I understand the size gain, but this hinders us from for example adding a standard cost to all non-spontaneous, non-exchange reactions without GPRs? And, are you sure we are not counting on that the model is irrev somewhere? I'm not sure, just concerned :)

**Comment by edkerk** [comment]
That's a fair point. So maybe only exchange reactions should be left out? Because exchange reactions are never enzyme-catalyzed (their transport reactions might).

**Comment by johan-gson** [comment]
Reasonable, agreed

**Comment by feiranl** [comment]
I also agree only exchange rxns are left out.

**Comment by edkerk** [comment]
Thanks for the feedback, it's changed now!

**Review by feiranl — APPROVED** [review]
LGTM!

**Pull request merged**
