### PR TITLE
docs: add link to tutorials in README

### PR DESCRIPTION
**Pull request by mihai-sysbio**
### Main improvements in this PR:

This PR resolves the last pending item in the checklist from #221 by adding the link to the tutorials directly in the README. Also, I have included a reference to the _full_ and _light_ versions of GECKO, and moved over a sentence that didn't quite belong in _About_ in my view.

**I hereby confirm that I have:**

- [x] Selected `develop` as a target branch (top left drop-down menu)

### CODE REVIEW

**Review by ae-tafur — APPROVED** [review]
Line29 requieres an update of minimum RAVEN version

**Comment by mihai-sysbio** [comment]
> This line requieres an update of minimum RAVEN version:
> 
> https://github.com/SysBioChalmers/GECKO/blob/900e2b76243f88d9e596d39b6933a8aa159902f6/README.md?plain=1#L29
> 
> Now is RAVEN v2.8.3

Great that you spotted this @ae-tafur! How about we skip mentioning the version here, since it's captured already in the installation script? Or should we say "latest version"?

**Comment by ae-tafur** [comment]
> Great that you spotted this @ae-tafur! How about we skip mentioning the version here, since it's captured already in the installation script? Or should we say "latest version"?

I think is ok to skip it. Also tutorials mention it.

**Comment by mihai-sysbio** [comment]
> I think is ok to skip it. Also tutorials mention it.

Good point, commit 7dedda98 removes the mentioning of the RAVEN version.

I will go ahead and merge this. If that was too eager, please reply here and I'll address any shortcomings in a distinct PR.

**Pull request merged**
