### PR TITLE
Refactor/avoid hard coding

### PR DESCRIPTION
**Pull request by IVANDOMENZAIN**
Avoid hard-coding of functions involved in the `getConstrainedModel` step of the pipeline. Model specific parameters are assigned by a global script (**`getModelParameters`**) that can be called every time that these parameters are needed in the whole GECKO workflow. Such parameters being the following:

- Sigma factor (Average enzyme saturation factor)
- Ptot (Total protein content in the cell [g protein/gDw])
- gR_exp (Minimum growth rate the model should grow at [1/h])
- org_name  (organism scientific name)
- keggID (organism KEGG ID)
- c_source (The name of the exchange reaction that supplies the model with carbon)
- bioRxn (Rxn Id for biomass pseudoreaction)
- enzyme_comp (Compartment name in which the added enzymes should be located)

This will allow a further generalization of the method, minimizing the amount of organism specific scripts that a user should create in order to generate a new ecModel (for a different organism) with the [ecModels generator pipeline](https://github.com/SysBioChalmers/ecModels).

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
@BenjaSanchez checked your additions and I like them, no more additions from side. Ready to be merged! :)

**Comment by IVANDOMENZAIN** [comment]
@BenjaSanchez I just realized that the README file should be updated accordingly to this pull request, specifically in the **Usage** section. Gonna do it in one commit.

**Comment by BenjaSanchez** [comment]
@IVANDOMENZAIN I thought I already did that? It was just one line (change `getModelParameters.m` instead of `enhanceGEM.m`), or you want to add further instructions?

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN I thought I already did that? It was just one line (change `getModelParameters.m` instead of `enhanceGEM.m`), or you want to add further instructions?

Done in c7c23fb

**Pull request merged**
