### PR TITLE
Feat/bayesian

### PR DESCRIPTION
**Pull request by johan-gson**
### Main improvements in this PR:
* Added the Bayesian. Note that it is currently limited, it is a bit hardcoded for Yeast-GEM and only works with light models - this is how the code in dlkcat was written. The full model is a bit more complicated to handle, the reactions have different names, sometimes you need to manipulate several reactions, etc., and I have not looked into what needs to be done about that. I have tested to run it once, it took 3-4 hours on my computer (8 + 8 cores), it converged in about 50 iterations - for the full it will take longer. Note that I added three files containing growth data etc. needed to run it.

**I hereby confirm that I have:**

- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [X] Selected `devel3` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by johan-gson** [comment]
@feiranl Could you test to run it on your computer and see that it does what it should?

**Review by edkerk — APPROVED** [review]
With room for improvement, the code seems to work okay. Good to have it combined with the other changes in `devel3`.

**Review by feiranl — COMMENTED** [review]
Sorry for the late reply. Seems fine.  I was not able to run several lines in the testworkflow. So I manually check these functions.

**Comment by mihai-sysbio** [comment]
I see this PR has been already merged, but @feiranl had some good feedback. Any suggestions @johan-gson @edkerk ?

**Comment by johan-gson** [comment]
This can be done, we just don't have time for it now + we don't have data for other models. Perhaps we could do it for different yeast species, I'm not sure. But time is the major problem, we only have a week until submission, the code should have been frozen by now :).

**Comment by johan-gson** [comment]
Eventually it would be nice to do it for human for example, although I think it may be challenging - I suspect that enzyme availability may not be the limiting factor for growth.

**Pull request merged**
