### PR TITLE
opt: Optimization of getEnzymeCodes and MatchKcats. 

### PR DESCRIPTION
**Pull request by johan-gson**
…ecko Light. The findInDBOld is still needed for KEGG matches, I haven't looked at that.

Some new optimizations were also introduced since there were other bottlenecks for yeast. I use containers.Map which may require a somewhat new matlab version.

### Main improvements in this PR:

**I hereby confirm that I have:**

- [ ] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [ ] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by johan-gson** [comment]
I had to add some additional optimizations for yeast. Check required matlab version for containers.Map, I use that. Also, I think it would be possible to optimize convertToEnzymeModel, that is pretty slow. The code is pretty similar to the GetMWandKCats in GeckoLight, the same optimizations could probably be done in that function. I also recommending creating lists of all mets/rxns to add, and add them in one call, instead of multiple calls. I tested that the old and new code produce the same kcat output, but some additional testing would be good.

**Comment by johan-gson** [comment]
eh, I managed to close it accidentally

**Review by ckitti — APPROVED** [review]
Reviewed GECKO model generation with iJN1462 GEM

**Review by ckitti — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
I think this was merged prematurely:
- the target branch should not be `master` but `devel`
- there is a bunch of code that is simply commented out (either remove it or use it)
- there is no associated issue that describes what the problem is so that it can be discussed
- the PR does not summarize the implementation

I would strongly advise reverting this merge to address the points above.

**Pull request merged**
