### PR TITLE
refactor: getConstrainedModel uses constrainPool directly

### PR DESCRIPTION
**Pull request by edkerk**
- refactor:
  - instead of parsing through `constrainEnzymes`, which is confusing as no enzymes are individually constrained, directly call `constrainPool`
  - `constrainPool` has alternative option where all enzymes are assumed non-measured 

To me it has been confusing that `constrainEnzymes` is called when only the pool is constrained. Perhaps there are good reasons for this, in that case please discard this PR.

### CODE REVIEW

**Comment by BenjaSanchez** [comment]
@edkerk `constrainEnzymes.m` is also used when constraining the model with proteomic data, it has inputs `pIDs` & `data` for this. That being said:
1. We should improve the documentation of both `constrainEnzymes.m` and `constrainPool.m` to explain this (connected to https://github.com/SysBioChalmers/GECKO/issues/51).
2. We should also add an example in the tool showing an integration with proteomics data, for instance in `/geckomat/utilities`, or possibly in a `/tutorials` folder.

**Comment by BenjaSanchez** [comment]
@edkerk the reason in `getConstrainedModel.m` we call `constrainEnzymes.m` and not `constrainPool.m` is because in the former we also perform some other changes, e.g. `scaleBioMass` and `fitGAM`.

**Comment by edkerk** [comment]
Just to clarify, I don't advocate for discarding `constrainEnzymes`, but just to directly call `constrainPool` by `getConstrainedModel` when it is generating the `ecModel_batch` model. I don't see why this has to run _through_ `constrainEnzymes`

**Comment by BenjaSanchez** [comment]
@edkerk the reason in `getConstrainedModel.m` we call `constrainEnzymes.m` and not `constrainPool.m` is because in the former we also perform some other changes, e.g. `scaleBioMass` and `fitGAM`.

**Pull request closed without merging**
