### PR TITLE
fix: getStandardKcat with multiple subSystems

### PR DESCRIPTION
**Pull request by edkerk**
### Main improvements in this PR:
- fix:
  - `getStandardKcat` handling models that have multiple subSystems assigned to the same reaction.

**I hereby confirm that I have:**

- [x] Selected `develop` as a target branch (top left drop-down menu)

### CODE REVIEW

**Review by ae-tafur — APPROVED** [review]

**Comment by mihai-sysbio** [comment]
The output of the action looks unexpected, but also doesn't seem to be caused by changes in this PR. Should it be investigated further (perhaps as a separate issue)?

> Model-specific DLKcat input stored at /home/m/actions-runner/_work/GECKO/GECKO/test/unit_tests/ecTestGEM/data/DLKcat_input_test.tsv
> Limit has been reached. Protein P5 seems to be problematic. Consider changing the kcat.

**Comment by ae-tafur** [comment]
I think is ok, this is output from the functions tested. `runDLKcat` (not 100% sure), and `flexibilizeProtConcs.m` (when a limit is set)

**Comment by ae-tafur** [comment]
> The output of the action looks unexpected, but also doesn't seem to be caused by changes in this PR. Should it be investigated further (perhaps as a separate issue)?
> 
> > Model-specific DLKcat input stored at /home/m/actions-runner/_work/GECKO/GECKO/test/unit_tests/ecTestGEM/data/DLKcat_input_test.tsv
> > Limit has been reached. Protein P5 seems to be problematic. Consider changing the kcat.

I think is ok, this is output from the functions tested. `runDLKcat` (not 100% sure), and `flexibilizeProtConcs` (when a limit is set)

**Comment by mihai-sysbio** [comment]
Other recent PRs have a much more verbose output when running the test suite, e.g. https://github.com/SysBioChalmers/GECKO/pull/295#issuecomment-1477424625 . Perhaps I missed something, but I was expecting a similar output here.

**Comment by ae-tafur** [comment]
> Other recent PRs have a much more verbose output when running the test suite, e.g. [#295 (comment)](https://github.com/SysBioChalmers/GECKO/pull/295#issuecomment-1477424625) . Perhaps I missed something, but I was expecting a similar output here.

Yeap, that was because a test was failing (check more [here](https://github.com/SysBioChalmers/RAVEN/pull/473)), but due to RAVEN reversibility assignment. This was fixed [here](https://github.com/SysBioChalmers/RAVEN/tree/v2.8.0)

**Pull request merged**
