### PR TITLE
Feat/get_subset_ecModel

### PR DESCRIPTION
**Pull request by IVANDOMENZAIN**
### Main improvements in this PR:

The function `getSubset_ecModel` has been added to the utilities repertoire. This function enables the obtention of a context-specific ecModel (strain/tissue/cell-line) from a general ecModel (at the species level, e.g. [ecHumanGEM](https://github.com/SysBioChalmers/ecModels/tree/feat/update_all_ecModels/ecHumanGEM/model)) without the need of running the whole GECKO pipeline on a previously constructed context-specific GEM. 

This function operates according to the following algorithm:
1. Identify the genes present in the general ecModel (`big_ecModel`) that are not included in the context-specific GEM (`smallGEM`).
2. Remove the identified genes and all model components related to them from the original `big_ecModel`.
3. Remove all remaining reactions and metabolites in the resulting `small_ecModel` that are not represented in or related to `smallGEM`(mostly non gene-associated transport and exchange reactions).
4. Remove all enzymes (and related information) that are not accounted for as pseudometabolites in `small_ecModel` anymore.

NOTE: This function relies on the `removeGenes` function available in the devel branch of the [RAVEN toolbox](https://github.com/SysBioChalmers/RAVEN/tree/devel). 

**I hereby confirm that I have:**

- [x] Tested my code with [all requirements](https://github.com/SysBioChalmers/GECKO) for running GECKO
- [x] Selected `devel` as a target branch (top left drop-down menu)

### CODE REVIEW

**Comment by IVANDOMENZAIN** [comment]
@johan-gson this PR is ready!

**Comment by IVANDOMENZAIN** [comment]
In order to test performance of this function a subset ecModel was obtained by using the context-specific [ecHOP92GEM](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels/blob/master/models/HOP92/HOP92.mat) and the current [ecHumanGEM](https://github.com/SysBioChalmers/ecModels/blob/feat/update_all_ecModels/ecHumanGEM/model/ecHumanGEM_batch.mat). This has reduced the computational time from hours to around 20 minutes in comparison to the pipeline available [here](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels) yielding a functional context-specific ecModel.

**Review by BenjaSanchez — APPROVED** [review]
looks good to me!

**Comment by BenjaSanchez** [comment]
disclaimer: I only took a look at the script logic and documentation, but I did not test it, as I don't have access to context-specific models. Probably @JonathanRob can give a better review in that regard ;)

**Comment by JonathanRob** [comment]
@IVANDOMENZAIN I hadn't thought of taking this approach (subsetting a generic ecGEM based on reactions present in a smaller GEM), but I think it's a great idea!

I found a few places in the code that could benefit from some changes - I will soon add the edits with a PR to this branch so you can take a look at them before incorporating anything.

**Comment by JonathanRob** [comment]
Ok, I made some changes to the `getSubset_ecModel` which are incorporated into PR #127. Let me know if you have any questions about those.

**Comment by IVANDOMENZAIN** [comment]
> In order to test performance of this function a subset ecModel was obtained by using the context-specific [HOP92-GEM](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels/blob/master/models/HOP92/HOP92.mat) and the current [ecHumanGEM](https://github.com/SysBioChalmers/ecModels/blob/feat/update_all_ecModels/ecHumanGEM/model/ecHumanGEM_batch.mat). This has reduced the computational time from hours to around 20 minutes in comparison to the pipeline available [here](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels) yielding a functional context-specific ecModel.

@johan-gson, the test case that I used for this function is detailed in the quoted comment. The problem here is that the general ecModel that we have available for `humanGEM` is based on its current version (v1.5.0) and the cell-line specific models and ecModels from the humanGEM paper are based on a version that is around 1 year-old. 

So it is expected that the newly generated ecModel (by this new approach) will be different to the one used for such paper ([ec-HOP92](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels/blob/master/models/HOP92/ecModel_batch.mat)). However, as a quality control, I've checked that the ecModel generated by this new function contains all of the enzymes present in the published ecHOP92, and yes! this is the case. 

If you would like to test the behavior of this pipeline even further, then I suggest the following approach:

1.- Generate a new tINIT model (for whatever cell-line or tissue) using `humanGEM` v.1.5.0 as a basis.
2.- Enhance the tINIT model with enzyme constraints using the [old pipeline](https://github.com/SysBioChalmers/EnzymeConstrained_humanModels), which relies in applying GECKO from scratch to the tINIT model.
3.- Generate another context-specific ecModel from the tINIT model, using this new utility function.
4.- Compare all components between the two context-specific ecModels.

One main advantage of this new pipeline is that it reduces the total computation time from some hours to ~60 seconds now. Moreover, this function has collected work, opinions and reviews from @BenjaSanchez, @mihai-sysbio, @JonathanRob and @IVANDOMENZAIN, so I think that this is a quite robust function so far.

**Pull request merged**
