### PR TITLE
style: adapt Matlab log

### PR DESCRIPTION
**Pull request by BenjaSanchez**
Following #123, I have adapted the GECKO pipeline to show a more concise log, see below for our use case of `ecYeast8.1.3`.

@IVANDOMENZAIN @mihai-sysbio I will proceed with generating an exchange flux file (as discussed with @IVANDOMENZAIN), but in the meantime let me know if this log is manageable for ecModels, or if we should continue to reduce it even more.

```matlab
***************************************************************
   GECKO: Adding enzyme constraints to a genome-scale model
***************************************************************

Getting genome-scale model ready... Done!

==================
Generating ecModel:
==================
Retrieving EC numbers....................................... Done!
Matching kcats....................................... Done!
Adding enzymes to reactions..................................................... Done!
Improving model with curated data......................................................................... Done!
Removing repeated rxn: r_1148 & r_1760_REV
Removing repeated rxn: r_1760 & r_1148_REV
Removing repeated rxn: r_0226No2 & r_0226No3
Removing repeated rxn: r_0438No1 & r_0438No2
Removing repeated rxn: r_0438No1 & r_0438No3
Removing repeated rxn: r_0438No1 & r_0438No4
Removing repeated rxn: r_0438No2 & r_0438No3
Removing repeated rxn: r_0438No2 & r_0438No4
Removing repeated rxn: r_0438No3 & r_0438No4
Removing repeated rxn: r_0439No1 & r_0439No2
Merging reactions: arm_r_0439 & r_0439No1
Merging reactions: arm_r_0543 & r_0543No1
Merging reactions: arm_r_1838 & r_1838No1
Removing unused protein: P00424
Removing unused protein: P18496
Removing unused protein: P22135
Removing unused protein: P32453
Removing unused protein: Q3E7B6
Removing incorrect pathways... Done!

==============================================================
Generating ecModel with shared pool assumption (ecModel_batch):
==============================================================
Calculating total abundance.................................................................... Done!
WARNING: Reaction r_4593_REV is not present in the reaction list

WARNING: Reaction r_4595_REV is not present in the reaction list

WARNING: Reaction r_4596_REV is not present in the reaction list

WARNING: Reaction r_4597_REV is not present in the reaction list

WARNING: Reaction r_4594_REV is not present in the reaction list

WARNING: Reaction r_4600_REV is not present in the reaction list

WARNING: Reaction r_4062 is not present in the reaction list

WARNING: Reaction r_4064 is not present in the reaction list

Matching data to enzymes in model... Done!
Estimating GAM.............................................................. Done!
Fitted GAM = 34 -> Error = 0.19859
Total protein amount measured = 0 g/gDW
Total enzymes measured = 0 enzymes
Enzymes in model with 0 g/gDW = 0 enzymes
Total protein amount not measured = 0.5 g/gDW
Total enzymes not measured = 816 enzymes
Total protein in model = 0.5 g/gDW
The ECmodel is overconstrained!
******************* Limiting Kcats curation *******************
*Iteration #1
 Automatic search // EC#: 5.4.99.7
  Protein:P38604 Rxn#:3194 name: lanosterol synthase (No1)
  prev_Kcat:0.0019367 new_Kcat:4.0763 CC:0.84835 Err:-47.7977%
*Iteration #2
 Automatic search // EC#: 6.3.5.3
  Protein:P38972 Rxn#:2437 name: 5'-phosphoribosylformyl glycinamidine synthetase (No1)
  prev_Kcat:0.05 new_Kcat:5.0675 CC:0.23689 Err:-35.5671%
*Iteration #3
 Automatic search // EC#: 4.2.1.20
  Protein:P00931 Rxn#:3593 name: tryptophan synthase (indoleglycerol phosphate) (No1)
  prev_Kcat:0.022301 new_Kcat:775.75 CC:0.11867 Err:-27.9123%
*Iteration #4
 Automatic search // EC#: 6.3.4.- 6.3.4.9 6.3.4.10 6.3.4.11 6.3.4.15
  Protein:P48445 Rxn#:2477 name: acetyl-CoA carboxylase, reaction (No1)
  prev_Kcat:1.23 new_Kcat:450000 CC:0.057317 Err:-23.7761%
*Iteration #5
 Automatic search // EC#: 2.1.1.14
  Protein:P05694 Rxn#:3224 name: methionine synthase (No1)
  prev_Kcat:0.33 new_Kcat:3.5 CC:0.047506 Err:-20.5076%
*Iteration #6
 Automatic search // EC#: 1.1.1.302
  Protein:P33312 Rxn#:2355 name: 2,5-diamino-6-ribosylamino-4(3H)-pyrimidinone 5'-phosphate reductase (NADPH) (No1)
  prev_Kcat:0.00066666 new_Kcat:0.00066667 CC:0.045129 Err:-20.5076%
*Iteration #7
 Automatic search // EC#: 4.1.1.65
  Protein:P39006 Rxn#:4097 name: PS decarboxylase (1-16:1, 2-16:1), mitochondrial membrane (No1)
  prev_Kcat:0.053334 new_Kcat:366.6667 CC:0.038195 Err:-17.4685%
*Iteration #8
 Automatic search // EC#: 2.3.1.15 2.3.1.42
  Protein:P36148 Rxn#:3821 name: glycerol-3-phosphate acyltransferase (16:1), ER membrane (No2)
  prev_Kcat:0.0918 new_Kcat:9.9733 CC:0.035165 Err:-14.5909%
*Iteration #9
 Automatic search // EC#: 2.3.3.14
  Protein:Q12122 Rxn#:3637 name: homocitrate synthase (No1)
  prev_Kcat:0.617 new_Kcat:5.133 CC:0.033518 Err:-12.0798%
*Iteration #10
 Automatic search // EC#: 2.3.3.10
  Protein:P54839 Rxn#:3065 name: hydroxymethylglutaryl CoA synthase (No1)
  prev_Kcat:0.415 new_Kcat:33.3333 CC:0.027098 Err:-9.7254%
***************************************************************
Fitting sigma factor....................... Done!
Sigma factor (fitted for growth on glucose): 0.44

=============
Saving models:
=============
Saving ecYeastGEM8.1.3:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Saving ecYeastGEM_batch8.1.3:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
```

### CODE REVIEW

**Comment by mihai-sysbio** [comment]
This looks great @BenjaSanchez !
If I am allowed to be picky, my personal choice would be to remove the empty lines surrounding `WARNING`s if possible. 
Also, the last part of the output is a bit repetitive but I'm not sure if something can be done about it:
>Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.
Saving ecYeastGEM_batch8.1.3:
Converting RAVEN structure to COBRA..
Each model.subSystems{x} is a character array, and this format is retained.
Document written
Each model.subSystems{x} is a character array, and this format is retained.

**Comment by BenjaSanchez** [comment]
@mihai-sysbio I agree with both preferences you mention, but in both cases this is not output from GECKO: The first case is a RAVEN warning from `setParam.m` that AFAIK cannot be customized, and the second case is from COBRA's `writeCbModel.m`. In both cases, the messages are specific to the yeast model, and will probably not show up for other models.

On a side note, we should probably address the root of these warnings for the yeast model in separate PRs, but in terms of message output, I think it's better to preserve the printed output from the associated toolboxes instead of e.g. silencing it or editing it to suit our pipeline's styling preferences.

**Comment by BenjaSanchez** [comment]
@IVANDOMENZAIN added the generation of the exchange flux file, as discussed. The PR is now ready for review, let me know if I'm missing anything.

**Comment by IVANDOMENZAIN** [comment]
> @IVANDOMENZAIN added the generation of the exchange flux file, as discussed. The PR is now ready for review, let me know if I'm missing anything.

The whole output looks nice and neat. I agree on your idea of addressing the warnings in the models saving step as a separate PR. 

Something to notice is the final growth rate displayed in the exchange fluxes file, which does not correspond to the one provided as experimental value in the `getModelParameters` function. This suggests a revision of the constraining steps in `getConstrainedModel`, particularly on the sigma fitter, however this is material for another PR.

Screen Shot 2021-02-01 at 14 15 52

**Review by IVANDOMENZAIN — APPROVED** [review]

**Pull request merged**
